// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGq9FN5Zcqt-5wzIOsISON_aRQJwIQiaM',
    appId: '1:921457321019:web:0d1ed66791bb847767e81e',
    messagingSenderId: '921457321019',
    projectId: 'myapp-191b8',
    authDomain: 'myapp-191b8.firebaseapp.com',
    storageBucket: 'myapp-191b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFBo4OMASXx9LEiCoPlY6foOEs7nG1LU',
    appId: '1:921457321019:android:ce70afe93a4a52b867e81e',
    messagingSenderId: '921457321019',
    projectId: 'myapp-191b8',
    storageBucket: 'myapp-191b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZDtzGqYhUaGiYDKm6Ip2SWRUq8f6SEg',
    appId: '1:921457321019:ios:0f71bec65613763567e81e',
    messagingSenderId: '921457321019',
    projectId: 'myapp-191b8',
    storageBucket: 'myapp-191b8.firebasestorage.app',
    iosBundleId: 'com.example.shourAlena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZDtzGqYhUaGiYDKm6Ip2SWRUq8f6SEg',
    appId: '1:921457321019:ios:0f71bec65613763567e81e',
    messagingSenderId: '921457321019',
    projectId: 'myapp-191b8',
    storageBucket: 'myapp-191b8.firebasestorage.app',
    iosBundleId: 'com.example.shourAlena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGq9FN5Zcqt-5wzIOsISON_aRQJwIQiaM',
    appId: '1:921457321019:web:f5ed37bc4bf4e36067e81e',
    messagingSenderId: '921457321019',
    projectId: 'myapp-191b8',
    authDomain: 'myapp-191b8.firebaseapp.com',
    storageBucket: 'myapp-191b8.firebasestorage.app',
  );
}
